services:
  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB: taskflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - taskflow_postgres_data:/var/lib/postgresql/data

volumes:
  taskflow_postgres_data: