services:
  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB: taskflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - taskflow_postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: taskflow-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - taskflow_minio_data:/data

volumes:
  taskflow_postgres_data:
  taskflow_minio_data: